#!/usr/bin/env bash

set -e

pushd "$(realpath "$(dirname "$0")")"

mkdir -p build/wasm

if [ ! -d build/emsdk ]; then
	git clone https://github.com/emscripten-core/emsdk.git build/emsdk
fi

pushd build/emsdk
git pull
./emsdk install 3.0.0
./emsdk activate 3.0.0
source ./emsdk_env.sh
popd # build/emsdk

pushd build/wasm
emcmake cmake -DCMAKE_BUILD_TYPE=Release ../../..
make -j
cp QMC2-wasm/QMC2{-legacy.js,-wasm.js,-wasm.wasm} ../../../public/
popd # build/wasm

popd
